services:
  - type: web
    name: assistente-puerperio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    plan: free
    region: oregon
    autoDeploy: true
